name       : plata-theme
version    : 0.4.8
release    : 5
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.4.8/plata-theme-0.4.8.tar.bz2 : da8d937c95310fde1f24acc0d636c0671d99824e14817e36f48c0aa18b89d052
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
