name       : plata-theme
version    : 0.9.7
release    : 34
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.9.7/plata-theme-0.9.7.tar.gz : 343834e96e9c945ee7941d89829d04f4681dc9a6f277a56b2f322cc893e9d998
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libmarco-private)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-Gtk-3.2x-4.0-Budgie-desktop-Stop-using-action.patch
    %patch -p1 < $pkgfiles/0001-Revert-Gtk-3.2x-4.0-Budgie-desktop-Shrink-the-Raven-.patch
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
