name       : plata-theme
version    : 0.5.8
release    : 15
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.5.8/plata-theme-0.5.8.tar.bz2 : 3f4aa97a463cd84feec7fe4e20185b4b02eabf0f7386b74f8aa4dae9077afcc6
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
