name       : plata-theme
version    : 0.4.7.1
release    : 4
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.4.7.1/plata-theme-0.4.7.1.tar.bz2 : 5165f8fa4b3f60f967ae33cd88fc2126635502489d228e6cf6990c2797bdf6eb
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
