name       : plata-theme
version    : 0.9.3
release    : 30
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.9.3/plata-theme-0.9.3.tar.gz : 5fa35fb4e8de3bfb4bbfcf3713e66a6a7c3eb7c9c2b1bcf92c5f4afa5bc19ae6
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libmarco-private)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-Gtk-3.2x-4.0-Budgie-desktop-Stop-using-action.patch
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
