name       : plata-theme
version    : 0.8.2
release    : 23
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.8.2/plata-theme-0.8.2.tar.gz : d059b0ae968204a8c124c114dc2f064750e0e18704c0c8d0fd90d1590891b015
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    %apply_patches
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
