name       : plata-theme
version    : 0.9.9
release    : 37
source     :
    - https://gitlab.com/tista500/plata-theme/-/archive/0.9.9/plata-theme-0.9.9.tar.bz2 : 19e40dfee94a47bb05860126d43e77c04e8f1b9701d2820ed615a9a0ca3bf067
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : A Gtk+ theme based on Material Design Refresh.
description: |
    A Gtk+ theme based on Material Design Refresh.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libmarco-private)
    - inkscape
    - sassc
rundeps    :
    - font-roboto-ttf
setup      : |
    %apply_patches
    # Josh: Do not remove gtk_next. I want this for Budgie 11 development.
    %autogen \
        --enable-plank \
        --enable-gtk_next \
        --enable-telegram \
        --enable-tweetdeck \
        --disable-cinnamon \
        --disable-gtk_legacy \
        --disable-openbox \
        --disable-unity \
        --with-selection_color=#5294e2 \
        --with-accent_color=#84beea \
        --with-suggestion_color=#4fa2e1 \
        --with-destruction_color=#f05f7e
build      : |
    %make
install    : |
    %make_install
